#!/bin/sh
#
# (c) Copyright EUMETSAT 2010
# (a) guillaume.aubert@eumetsat.int
#
###########################################################
## Part 1: You may want to change some of these definitions
###########################################################

##########################
## MDEXPORTER home directory
##########################
#default value
_MDEXPORTER_HOME=..
MDEXPORTER_HOME=${MDEXPORTER_HOME:-$_MDEXPORTER_HOME}

#############################
## To activate some debugging 
## set it to yes
#############################
MD_DEBUG=no

########################
## Java optional options
########################
JAVA_OPTS="-Xms64m -Xmx256m"
#JAVA_OPTS="-Xms64m -Xmx256m -Xdebug -Xrunjdwp:transport=dt_socket,address=7000,server=y,suspend=n"
#JAVA_OPTS=""

########################
## Java Env
########################
if [ ! -f "$JAVA_HOME/bin/java" ]; then
   echo "Please add $JAVA_HOMEin your env. JAVA_HOME needs to point to a JAVA 1.6 JVM or further"
   exit 1
fi
java=$JAVA_HOME/bin/java

#################################
## if DATAREPOSITORY_HOME is relative,
## build the absolute path
#################################
D=`dirname "$MDEXPORTER_HOME"`
B=`basename "$MDEXPORTER_HOME"`
MDEXPORTER_HOME="`cd \"$D\" 2>/dev/null && pwd || echo \"$D\"`/$B"

#echo "MDEXPORTER_HOME is in $MDEXPORTER_HOME"

########################
## set distribution dirs
########################
lib=$MDEXPORTER_HOME/lib
conf=$MDEXPORTER_HOME/conf

#######################################################################
## Part 2: You probably don't want to change anything beyond this point
#######################################################################

########################
## check dirs
########################
if [ ! -d "$lib" -o  ! -d "$conf" ]; then
   echo "The env var MDEXPORTER_HOME=$MDEXPORTER_HOME is not set correclty. Please set it to the metadata exporter HOME dir."
   exit 1
fi

#########################################
## Set the starter classpath
## if will be different for a cygwin prog
#########################################
if uname | grep -i cygwin > /dev/null; then
  # windows world so change path to win path for libs and separator is ;
  for n in `find $lib/*.jar`; do
     STARTERPATH=$STARTERPATH";"`cygpath --windows $n`
  done

  #change the path for conf to be windows paths
  conf=`cygpath --windows $conf`

  #change MDEXPORTER_HOME to a win compliant path before to pass as an argument for the VM
  MD_HOME=`cygpath --windows $MDEXPORTER_HOME`

  #issue on windows file:/ must have one slash
  LOG4J_CONF="file:/$conf/log4j.properties"

else
  # any other unix separator is ;
  for n in `find $lib/*.jar`; do
       STARTERPATH=$STARTERPATH":"$n
  done

  MD_HOME=$MDEXPORTER_HOME

  #issue on unix file:// must have 2 slashes
  LOG4J_CONF="file://$conf/log4j.properties"
fi

###########################
## check if MD_DEBUG is set
###########################
if [ $MD_DEBUG = "yes" -o $MD_DEBUG = "YES" ]; then
 log_debug=DEBUG
else
 log_debug=INFO
fi


###################
## Add java options
###################
JAVA_OPTS=$JAVA_OPTS" -Dmd.home=$MD_HOME"
JAVA_OPTS=$JAVA_OPTS" -Dmd.debug=$MD_DEBUG"
JAVA_OPTS=$JAVA_OPTS" -Dmd.log.debug=$log_debug"
JAVA_OPTS=$JAVA_OPTS" -Dlog4j.configuration=$LOG4J_CONF"


java $JAVA_OPTS \
      -cp "$STARTERPATH" org.eumetsat.dcpc.md.export.CMDRunner $*
